[redshift]
temp-day=5700
temp-night=3500
transition=1

# Skips GeoClue2
location-provider=manual
adjustment-method=randr

# Quezon City, Philippines
[manual]
lat=14.65
lon=121.05

# note: this is outside of redshift folder because mint's AppArmor denies access to redshift folder